from __future__ import annotations


DEFAULT_LOCALE = "en"
SUPPORTED_LOCALES = ("en", "ru")


TRANSLATIONS: dict[str, dict[str, str]] = {
    "en": {
        "app.title": "More than HP Manager (c) by LostPersona",
        "app.header": "More than HP Manager",
        "app.subtitle": "Track HP, money, spell slots, and initiative, detach OBS windows, and sync values from a Google Doc.",
        "language.label": "Language",
        "language.en": "English",
        "language.ru": "Russian",
        "card.add_player": "Add Player",
        "card.players": "Players",
        "card.sync": "Document Sync Preview",
        "card.overlay_settings": "Fill Settings",
        "label.name": "Name",
        "label.current": "Current",
        "label.max": "Max",
        "label.temp": "Temp",
        "label.step": "Step",
        "label.source": "Google Doc link",
        "label.poll_seconds": "Poll seconds",
        "label.overlay_ratio": "Fill shape",
        "label.money_layout": "Money layout",
        "label.money_order": "Coin order",
        "label.spell_display_count": "Shown spell levels",
        "label.spell_render_mode": "Spell render mode",
        "label.show_spell_level_headers": "Spell level headers",
        "label.hp_font_size": "HP font size",
        "label.temp_hp_font_size": "Temp HP font size",
        "label.money_font_size": "Money font size",
        "label.spell_level_font_size": "Spell level font size",
        "label.spell_font_size": "Spell value font size",
        "label.spell_cell_scale": "Spell cell size",
        "label.spell_pip_scale": "Spell square size",
        "label.window_behavior": "Window behavior",
        "label.window_backgrounds": "Window backgrounds",
        "action.add_to_dashboard": "Add To Dashboard",
        "action.player_window": "Player Window",
        "action.hide_window": "Hide Window",
        "action.overlay": "Fill",
        "action.hide_overlay": "Hide Fill",
        "action.money_window": "Money Window",
        "action.hide_money_window": "Hide Money Window",
        "action.edit_money": "Money",
        "action.spell_window": "Spell Window",
        "action.hide_spell_window": "Hide Spell Window",
        "action.edit_spell_slots": "Spell Slots",
        "action.apply": "Apply",
        "action.close": "Close",
        "action.remove": "Remove",
        "action.damage": "- HP",
        "action.heal": "+ HP",
        "action.fetch_doc": "Fetch Doc Now",
        "action.apply_parsed_lines": "Apply Parsed Lines",
        "action.load_example": "Load Example",
        "action.hide_sync": "Hide Sync",
        "action.show_sync": "Show Sync",
        "action.show_settings": "Show Settings",
        "action.hide_settings": "Hide Settings",
        "action.open_initiative_tracker": "Open Initiative Tracker",
        "players.header": "Each player card keeps HP, fill, and spell slot controls together so OBS actions stay close to the character.",
        "initiative.header": "Initiative Tracker",
        "initiative.subtitle": "Build turn order with portraits, manage rounds quickly, and keep a reusable portrait library beside the app.",
        "initiative.window_title": "Initiative Tracker",
        "initiative.obs_title": "Initiative Order",
        "initiative.card.add_combatant": "Add Character",
        "initiative.card.encounter": "Turn Order",
        "initiative.card.turn_controls": "Run Encounter",
        "initiative.card.combatant_library": "Saved Characters",
        "initiative.card.library": "Portraits",
        "initiative.label.initiative": "Initiative",
        "initiative.label.from_players": "Add From HP Players",
        "initiative.label.search": "Search portraits",
        "initiative.label.preview": "Selected portrait preview",
        "initiative.library_header": "Double-click a saved character to add it to the encounter.",
        "initiative.add_helper": "Type a name, choose a portrait if you want one, then add or save the character.",
        "initiative.options_header": "OBS & tracker options",
        "initiative.action.add_combatant": "Add To Encounter",
        "initiative.action.add_from_players": "Add Player To Encounter",
        "initiative.action.save_selected_player_to_library": "Save Selected Player",
        "initiative.action.save_to_library": "Save Character",
        "initiative.action.add_selected_library": "Add Saved Character",
        "initiative.action.set_library_portrait": "Set Saved Portrait",
        "initiative.action.delete_library_entry": "Delete Saved Character",
        "initiative.action.start": "Start & Sort",
        "initiative.action.previous_turn": "Previous Turn",
        "initiative.action.next_turn": "Next Turn",
        "initiative.action.reset": "Reset To Round 1",
        "initiative.action.clear": "Clear Encounter",
        "initiative.action.show_obs": "Open OBS Window",
        "initiative.action.hide_obs": "Hide OBS Window",
        "initiative.action.import_portraits": "Import Portraits",
        "initiative.action.delete_portrait": "Delete Portrait",
        "initiative.action.refresh_library": "Refresh Library",
        "initiative.action.use_for_new": "Use Portrait",
        "initiative.action.use_selected_portrait": "Set Portrait",
        "initiative.action.clear_portrait": "Clear Portrait",
        "initiative.action.move_up": "Earlier",
        "initiative.action.move_down": "Later",
        "initiative.show_hp_player_import": "Show HP manager import section",
        "initiative.obs_topmost": "Keep initiative OBS window above other apps",
        "initiative.obs_background": "Show initiative OBS background",
        "initiative.obs_current_border": "Show gold border on current OBS portrait",
        "initiative.obs_visible_slots": "Visible portraits in initiative OBS window",
        "initiative.round_label": "Round {round_number}",
        "initiative.combatant_count": "{count} total",
        "initiative.current_turn": "Current: {name}",
        "initiative.not_started": "Encounter not started",
        "initiative.empty_obs": "Add combatants in the Initiative Tracker to show turn order here.",
        "initiative.initiative_badge": "INIT {initiative}",
        "initiative.no_portrait": "No Portrait",
        "initiative.no_portrait_selected": "No portrait selected.",
        "initiative.current_marker": "Current turn",
        "initiative.ready_marker": "Ready",
        "initiative.encounter_summary_idle": "{count} combatant(s) ready. Start & Sort will order them by initiative.",
        "initiative.encounter_summary_started": "{count} combatant(s), round {round_number}, current: {current}.",
        "initiative.status.ready": "Initiative tracker ready.",
        "initiative.status.added": "Added {name} to the initiative tracker.",
        "initiative.status.inserted": "Inserted {name} into the active turn order.",
        "initiative.status.updated": "Updated {name}.",
        "initiative.status.removed": "Removed {name} from the initiative tracker.",
        "initiative.status.saved_to_library": "Saved {name} to the combatant library.",
        "initiative.status.library_portrait_updated": "Updated saved portrait for {name}.",
        "initiative.status.deleted_library_entry": "Removed {name} from the combatant library.",
        "initiative.status.reordered": "Encounter order updated.",
        "initiative.status.started": "Encounter started and sorted by initiative.",
        "initiative.status.reset": "Encounter reset to round 1.",
        "initiative.status.cleared": "Encounter cleared.",
        "initiative.status.turn_advanced": "Turn advanced to {name}.",
        "initiative.status.turn_rewound": "Turn moved back to {name}.",
        "initiative.status.no_combatants": "Add at least one combatant first.",
        "initiative.status.no_library_selected": "Select a saved combatant first.",
        "initiative.status.no_portrait_selected": "Select a portrait from the library first.",
        "initiative.status.selected_portrait_ready": "Selected portrait will be used for the next combatant or reassignment.",
        "initiative.status.portrait_assigned": "Assigned portrait to {name}.",
        "initiative.status.portrait_cleared": "Cleared portrait for {name}.",
        "initiative.status.imported_portraits": "Imported {count} portrait(s) into the local library.",
        "initiative.status.deleted_portrait": "Portrait deleted from the local library.",
        "initiative.status.no_player_selected": "Select a player from the HP roster first.",
        "initiative.status.import_visibility_saved": "HP manager import visibility updated.",
        "initiative.status.obs_settings_saved": "Initiative OBS window settings updated.",
        "initiative.dialog.import_title": "Import portraits",
        "initiative.dialog.image_files": "Image files",
        "initiative.dialog.all_files": "All files",
        "initiative.dialog.delete_title": "Delete portrait",
        "initiative.dialog.delete_confirm": "Delete the selected portrait from the local portrait library?",
        "initiative.dialog.delete_readonly": "Built-in portraits come from bundled assets and cannot be deleted from inside the app.",
        "initiative.dialog.delete_failed": "The selected portrait could not be deleted.",
        "initiative.dialog.clear_title": "Clear encounter",
        "initiative.dialog.clear_confirm": "Remove all combatants from the current encounter?",
        "spell.render.text": "Numeric cells",
        "spell.render.pips": "Square slots",
        "spell.show_level_headers": "Show spell level headers",
        "sync.enable": "Enable automatic Google Doc sync",
        "sync.only_existing": "Only update existing players from sync data",
        "sync.help": "Only lines between `>>>` markers are parsed. Each character entry must start with `Name:` and can then include `Health:`, `Coins:`, and `Spell Slots:` in any order.\nMissing values default to zero, money supports `cc`, `sc`, `gc`, and spell slots use levels `1: current/max` through `9: current/max`.\nEnable \"Only update existing players\" to ignore unknown names instead of adding new dashboard entries from sync text.\nWhen sync mode is enabled, manual editing controls are hidden and the dashboard becomes display-focused.",
        "money.cc": "CC",
        "money.sc": "SC",
        "money.gc": "GC",
        "money.layout.stacked": "Separate lines",
        "money.layout.inline": "One line",
        "money.order.cc_sc_gc": "Copper, Silver, Gold",
        "money.order.gc_sc_cc": "Gold, Silver, Copper",
        "overlay.show_title": "Show character name above fill",
        "overlay.player_windows_topmost": "Keep player, money, and spell windows above other apps",
        "overlay.fill_windows_topmost": "Keep fill windows above other apps",
        "overlay.player_window_background": "Show HP window background",
        "overlay.money_window_background": "Show money window background",
        "overlay.spell_window_background": "Show spell window background",
        "overlay.fill_window_background": "Show fill frame/background",
        "overlay.aspect.1:1": "Square (1:1)",
        "overlay.aspect.4:3": "Rectangle (4:3)",
        "overlay.aspect.3:4": "Portrait (3:4)",
        "overlay.window_title": "Fill: {name}",
        "player.window_title": "HP: {name}",
        "money.window_title": "Money: {name} ",
        "money.editor_title": "Money Editor: {name} ",
        "spell.window_title": "Spell Slots: {name}",
        "spell.editor_title": "Spell Slots Editor: {name}",
        "spell.level_label": "Level {level}",
        "player.temp_hp": "Temp HP: {temp_hp}",
        "player.summary": "Visible HP: {current_hp}/{max_hp}    Temp: {temp_hp}",
        "player.default_name": "Unnamed",
        "status.ready": "Ready",
        "status.added": "Added {name}.",
        "status.removed": "Removed {name}.",
        "status.money_saved": "Money updated for {name}.",
        "status.spell_slots_saved": "Spell slots updated for {name}.",
        "status.sync_applied": "Applied {applied} sync item(s) from the preview.",
        "status.sync_applied_skipped": "Applied {applied} sync item(s) from the preview and skipped {skipped} unknown name(s).",
        "status.sync_applied_with_issues": "Applied {applied} sync item(s), with {issues} parse issue(s).",
        "status.sync_applied_with_issues_skipped": "Applied {applied} sync item(s), skipped {skipped} unknown name(s), with {issues} parse issue(s).",
        "status.example_loaded": "Loaded example sync lines.",
        "status.language_changed": "Language switched to {language}.",
        "status.fetching_doc": "Fetching Google Doc...",
        "status.doc_fetched": "Fetched Google Doc and applied {applied} sync item(s).",
        "status.doc_fetched_skipped": "Fetched Google Doc, applied {applied} sync item(s), and skipped {skipped} unknown name(s).",
        "status.fetch_failed": "Google Doc fetch failed: {message}",
        "status.sync_source_missing": "Add a Google Doc link first.",
        "status.sync_hidden": "Document sync preview hidden.",
        "status.sync_shown": "Document sync preview shown.",
        "status.settings_hidden": "Fill settings hidden.",
        "status.settings_shown": "Fill settings shown.",
        "status.overlay_settings_saved": "Fill settings updated.",
        "dialog.parse_issues.title": "Parse issues",
        "dialog.parse_issues.message": "Line {line_number}: could not parse '{line}'",
        "dialog.fetch_failed.title": "Google Doc fetch failed",
        "error.sync.no_link": "No Google Doc link was provided.",
        "error.sync.bad_link": "Could not extract a Google Doc ID from the provided link.",
        "error.sync.access_denied": "Google denied access to the document export. Make sure the doc is shared so the app can read it.",
        "error.sync.not_found": "Google Doc not found. Check the link and document permissions.",
        "error.sync.http": "Google Doc export failed with HTTP {code}.",
        "error.sync.network": "Could not reach Google Docs: {reason}",
        "error.sync.html_response": "Received an HTML page instead of plain text. The document may require sign-in or block text export.",
        "error.sync.unknown": "Unexpected sync error: {message}",
    },
    "ru": {
        "app.title": "More than HP Manager (c) by LostPersona",
        "app.header": "More than HP Manager",
        "app.subtitle": "Отслеживайте HP, деньги, ячейки заклинаний и инициативу, выносите окна для OBS и синхронизируйте значения из Google Doc.",
        "language.label": "Язык",
        "language.en": "Английский",
        "language.ru": "Русский",
        "card.add_player": "Добавить игрока",
        "card.players": "Игроки",
        "card.sync": "Предпросмотр синхронизации",
        "card.overlay_settings": "Настройки заливки",
        "label.name": "Имя",
        "label.current": "Текущее",
        "label.max": "Макс.",
        "label.temp": "Врем.",
        "label.step": "Шаг",
        "label.source": "Ссылка на Google Doc",
        "label.poll_seconds": "Интервал опроса",
        "label.overlay_ratio": "Форма заливки",
        "label.money_layout": "Расположение монет",
        "label.money_order": "Порядок монет",
        "label.spell_display_count": "Показывать уровни ячеек",
        "label.spell_render_mode": "Режим отображения ячеек",
        "label.show_spell_level_headers": "Заголовки уровней ячеек",
        "label.hp_font_size": "Размер шрифта HP",
        "label.temp_hp_font_size": "Размер шрифта врем. HP",
        "label.money_font_size": "Размер шрифта денег",
        "label.spell_level_font_size": "Размер шрифта уровней ячеек",
        "label.spell_font_size": "Размер шрифта значений ячеек",
        "label.spell_cell_scale": "Размер ячеек заклинаний",
        "label.spell_pip_scale": "Размер квадратов ячеек",
        "label.window_behavior": "Поведение окон",
        "label.window_backgrounds": "Фон окон",
        "action.add_to_dashboard": "Добавить на панель",
        "action.player_window": "Окно HP",
        "action.hide_window": "Скрыть окно HP",
        "action.overlay": "Заливка",
        "action.hide_overlay": "Скрыть заливку",
        "action.money_window": "Окно денег",
        "action.hide_money_window": "Скрыть окно денег",
        "action.edit_money": "Деньги",
        "action.spell_window": "Окно ячеек",
        "action.hide_spell_window": "Скрыть окно ячеек",
        "action.edit_spell_slots": "Ячейки заклинаний",
        "action.apply": "Применить",
        "action.close": "Закрыть",
        "action.remove": "Удалить",
        "action.damage": "- HP",
        "action.heal": "+ HP",
        "action.fetch_doc": "Загрузить документ",
        "action.apply_parsed_lines": "Применить строки",
        "action.load_example": "Загрузить пример",
        "action.hide_sync": "Скрыть синхронизацию",
        "action.show_sync": "Показать синхронизацию",
        "action.show_settings": "Показать настройки",
        "action.hide_settings": "Скрыть настройки",
        "action.open_initiative_tracker": "Открыть трекер инициативы",
        "players.header": "В карточке игрока собраны HP, заливка и ячейки заклинаний, чтобы OBS-элементы были рядом с персонажем.",
        "initiative.header": "Трекер инициативы",
        "initiative.subtitle": "Собирайте порядок ходов с портретами, быстро ведите раунды и используйте общую библиотеку портретов рядом с приложением.",
        "initiative.window_title": "Трекер инициативы",
        "initiative.obs_title": "Порядок ходов",
        "initiative.card.add_combatant": "Добавить персонажа",
        "initiative.card.encounter": "Порядок ходов",
        "initiative.card.turn_controls": "Ведение схватки",
        "initiative.card.combatant_library": "Сохраненные персонажи",
        "initiative.card.library": "Портреты",
        "initiative.label.initiative": "Инициатива",
        "initiative.label.from_players": "Добавить из игроков HP",
        "initiative.label.search": "Поиск портретов",
        "initiative.label.preview": "Предпросмотр выбранного портрета",
        "initiative.library_header": "Двойной щелчок по сохраненному персонажу добавит его в схватку.",
        "initiative.add_helper": "Введите имя, при желании выберите портрет, а затем добавьте или сохраните персонажа.",
        "initiative.options_header": "OBS и настройки трекера",
        "initiative.action.add_combatant": "Добавить в схватку",
        "initiative.action.add_from_players": "Добавить игрока в схватку",
        "initiative.action.save_selected_player_to_library": "Сохранить выбранного игрока",
        "initiative.action.save_to_library": "Сохранить персонажа",
        "initiative.action.add_selected_library": "Добавить сохраненного персонажа",
        "initiative.action.set_library_portrait": "Назначить портрет",
        "initiative.action.delete_library_entry": "Удалить сохраненного персонажа",
        "initiative.action.start": "Старт и сортировка",
        "initiative.action.previous_turn": "Предыдущий ход",
        "initiative.action.next_turn": "Следующий ход",
        "initiative.action.reset": "Сбросить к 1 раунду",
        "initiative.action.clear": "Очистить схватку",
        "initiative.action.show_obs": "Открыть OBS-окно",
        "initiative.action.hide_obs": "Скрыть OBS-окно",
        "initiative.action.import_portraits": "Импортировать портреты",
        "initiative.action.delete_portrait": "Удалить портрет",
        "initiative.action.refresh_library": "Обновить библиотеку",
        "initiative.action.use_for_new": "Использовать портрет",
        "initiative.action.use_selected_portrait": "Назначить портрет",
        "initiative.action.clear_portrait": "Очистить портрет",
        "initiative.action.move_up": "Раньше",
        "initiative.action.move_down": "Позже",
        "initiative.show_hp_player_import": "Показывать импорт из HP manager",
        "initiative.obs_topmost": "Держать OBS-окно инициативы поверх других приложений",
        "initiative.obs_background": "Показывать фон OBS-окна инициативы",
        "initiative.obs_current_border": "Показывать золотую обводку текущего портрета в OBS",
        "initiative.obs_visible_slots": "Сколько портретов показывать в OBS-окне инициативы",
        "initiative.round_label": "Раунд {round_number}",
        "initiative.combatant_count": "Всего: {count}",
        "initiative.current_turn": "Сейчас ходит: {name}",
        "initiative.not_started": "Схватка еще не начата",
        "initiative.empty_obs": "Добавьте участников в трекер инициативы, чтобы здесь появился порядок ходов.",
        "initiative.initiative_badge": "ИНИ {initiative}",
        "initiative.no_portrait": "Нет портрета",
        "initiative.no_portrait_selected": "Портрет не выбран.",
        "initiative.current_marker": "Текущий ход",
        "initiative.ready_marker": "Готов",
        "initiative.encounter_summary_idle": "Готово участников: {count}. «Старт и сортировка» выстроит их по инициативе.",
        "initiative.encounter_summary_started": "Участников: {count}, раунд {round_number}, сейчас ходит: {current}.",
        "initiative.status.ready": "Трекер инициативы готов.",
        "initiative.status.added": "{name} добавлен в трекер инициативы.",
        "initiative.status.inserted": "{name} вставлен в активный порядок ходов.",
        "initiative.status.updated": "{name} обновлен.",
        "initiative.status.removed": "{name} удален из трекера инициативы.",
        "initiative.status.saved_to_library": "{name} сохранен в библиотеку участников.",
        "initiative.status.library_portrait_updated": "Портрет сохраненного персонажа {name} обновлен.",
        "initiative.status.deleted_library_entry": "{name} удален из библиотеки участников.",
        "initiative.status.reordered": "Порядок схватки обновлен.",
        "initiative.status.started": "Схватка начата и отсортирована по инициативе.",
        "initiative.status.reset": "Схватка сброшена к первому раунду.",
        "initiative.status.cleared": "Схватка очищена.",
        "initiative.status.turn_advanced": "Ход передан: {name}.",
        "initiative.status.turn_rewound": "Ход возвращен: {name}.",
        "initiative.status.no_combatants": "Сначала добавьте хотя бы одного участника.",
        "initiative.status.no_library_selected": "Сначала выберите сохраненного участника.",
        "initiative.status.no_portrait_selected": "Сначала выберите портрет из библиотеки.",
        "initiative.status.selected_portrait_ready": "Выбранный портрет будет использован для следующего участника или переназначения.",
        "initiative.status.portrait_assigned": "Портрет назначен для {name}.",
        "initiative.status.portrait_cleared": "Портрет очищен для {name}.",
        "initiative.status.imported_portraits": "В локальную библиотеку импортировано портретов: {count}.",
        "initiative.status.deleted_portrait": "Портрет удален из локальной библиотеки.",
        "initiative.status.no_player_selected": "Сначала выберите игрока из HP-списка.",
        "initiative.status.import_visibility_saved": "Видимость импорта из HP manager обновлена.",
        "initiative.status.obs_settings_saved": "Настройки OBS-окна инициативы обновлены.",
        "initiative.dialog.import_title": "Импорт портретов",
        "initiative.dialog.image_files": "Файлы изображений",
        "initiative.dialog.all_files": "Все файлы",
        "initiative.dialog.delete_title": "Удаление портрета",
        "initiative.dialog.delete_confirm": "Удалить выбранный портрет из локальной библиотеки портретов?",
        "initiative.dialog.delete_readonly": "Встроенные портреты идут из bundled assets и не могут быть удалены из приложения.",
        "initiative.dialog.delete_failed": "Не удалось удалить выбранный портрет.",
        "initiative.dialog.clear_title": "Очистить схватку",
        "initiative.dialog.clear_confirm": "Удалить всех участников из текущей схватки?",
        "spell.render.text": "Числовые ячейки",
        "spell.render.pips": "Квадраты слотов",
        "spell.show_level_headers": "Показывать заголовки уровней ячеек",
        "sync.enable": "Включить автоматическую синхронизацию с Google Doc",
        "sync.only_existing": "Обновлять из синхронизации только существующих игроков",
        "sync.help": "Разбираются только строки между маркерами `>>>`. Каждая запись персонажа должна начинаться с `Имя:`, а дальше в любом порядке могут идти `Здоровье:`, `Монеты:` и `Ячейки заклинаний:`.\nОтсутствующие значения считаются нулевыми, для денег поддерживаются `cc`, `sc`, `gc` и русские `мм`, `см`, `зм`, а для ячеек уровни задаются как `1: текущее/макс` до `9: текущее/макс`.\nВключите \"Обновлять только существующих игроков\", чтобы неизвестные имена игнорировались и не создавали новых записей на панели.\nКогда режим синхронизации включен, ручные элементы редактирования скрываются, и панель работает как витрина значений.",
        "money.cc": "ММ",
        "money.sc": "СМ",
        "money.gc": "ЗМ",
        "money.layout.stacked": "Отдельные строки",
        "money.layout.inline": "Одна строка",
        "money.order.cc_sc_gc": "Медь, Серебро, Золото",
        "money.order.gc_sc_cc": "Золото, Серебро, Медь",
        "overlay.show_title": "Показывать имя персонажа над заливкой",
        "overlay.player_windows_topmost": "Держать окна игроков, денег и ячеек поверх других приложений",
        "overlay.fill_windows_topmost": "Держать окна заливки поверх других приложений",
        "overlay.player_window_background": "Показывать фон окна HP",
        "overlay.money_window_background": "Показывать фон окна денег",
        "overlay.spell_window_background": "Показывать фон окна ячеек",
        "overlay.fill_window_background": "Показывать фон/рамку заливки",
        "overlay.aspect.1:1": "Квадрат (1:1)",
        "overlay.aspect.4:3": "Прямоугольник (4:3)",
        "overlay.aspect.3:4": "Портрет (3:4)",
        "overlay.window_title": "Заливка: {name}",
        "player.window_title": "HP: {name} ",
        "money.window_title": "Деньги: {name}",
        "money.editor_title": "Деньги Редактор: {name}",
        "spell.window_title": "Ячейки заклинаний: {name}",
        "spell.editor_title": "Ячейки заклинаний Редактор: {name}",
        "spell.level_label": "Уровень {level}",
        "player.temp_hp": "Временные HP: {temp_hp}",
        "player.summary": "Видимые HP: {current_hp}/{max_hp}    Врем.: {temp_hp}",
        "player.default_name": "Без имени",
        "status.ready": "Готово",
        "status.added": "Игрок {name} добавлен.",
        "status.removed": "Игрок {name} удален.",
        "status.money_saved": "Деньги обновлены для {name}.",
        "status.spell_slots_saved": "Ячейки заклинаний обновлены для {name}.",
        "status.sync_applied": "Применено объектов синхронизации из предпросмотра: {applied}.",
        "status.sync_applied_skipped": "Применено объектов синхронизации: {applied}, пропущено неизвестных имен: {skipped}.",
        "status.sync_applied_with_issues": "Применено объектов синхронизации: {applied}, проблем парсинга: {issues}.",
        "status.sync_applied_with_issues_skipped": "Применено объектов синхронизации: {applied}, пропущено неизвестных имен: {skipped}, проблем парсинга: {issues}.",
        "status.example_loaded": "Пример строк синхронизации загружен.",
        "status.language_changed": "Язык переключен: {language}.",
        "status.fetching_doc": "Загрузка Google Doc...",
        "status.doc_fetched": "Google Doc загружен, применено объектов синхронизации: {applied}.",
        "status.doc_fetched_skipped": "Google Doc загружен, применено объектов синхронизации: {applied}, пропущено неизвестных имен: {skipped}.",
        "status.fetch_failed": "Не удалось загрузить Google Doc: {message}",
        "status.sync_source_missing": "Сначала добавьте ссылку на Google Doc.",
        "status.sync_hidden": "Предпросмотр синхронизации скрыт.",
        "status.sync_shown": "Предпросмотр синхронизации показан.",
        "status.settings_hidden": "Настройки заливки скрыты.",
        "status.settings_shown": "Настройки заливки показаны.",
        "status.overlay_settings_saved": "Настройки заливки обновлены.",
        "dialog.parse_issues.title": "Проблемы парсинга",
        "dialog.parse_issues.message": "Строка {line_number}: не удалось разобрать '{line}'",
        "dialog.fetch_failed.title": "Не удалось загрузить Google Doc",
        "error.sync.no_link": "Ссылка на Google Doc не указана.",
        "error.sync.bad_link": "Не удалось извлечь идентификатор Google Doc из указанной ссылки.",
        "error.sync.access_denied": "Google не дал доступ к экспорту документа. Убедитесь, что документ открыт для чтения приложением.",
        "error.sync.not_found": "Google Doc не найден. Проверьте ссылку и права доступа к документу.",
        "error.sync.http": "Экспорт Google Doc завершился ошибкой HTTP {code}.",
        "error.sync.network": "Не удалось связаться с Google Docs: {reason}",
        "error.sync.html_response": "Вместо текста пришла HTML-страница. Возможно, документ требует входа или блокирует текстовый экспорт.",
        "error.sync.unknown": "Непредвиденная ошибка синхронизации: {message}",
    },
}


def normalize_locale(locale: str | None) -> str:
    if locale in SUPPORTED_LOCALES:
        return locale
    return DEFAULT_LOCALE


class Localizer:
    def __init__(self, locale: str | None = None) -> None:
        self.locale = normalize_locale(locale)

    def set_locale(self, locale: str) -> None:
        self.locale = normalize_locale(locale)

    def text(self, key: str, **kwargs: object) -> str:
        value = TRANSLATIONS.get(self.locale, {}).get(key)
        if value is None:
            value = TRANSLATIONS[DEFAULT_LOCALE].get(key, key)
        return value.format(**kwargs)

    def locale_name(self, locale: str) -> str:
        code = normalize_locale(locale)
        return self.text(f"language.{code}")
