from __future__ import annotations


DEFAULT_LOCALE = "en"
SUPPORTED_LOCALES = ("en", "ru")


TRANSLATIONS: dict[str, dict[str, str]] = {
    "en": {
        "app.title": "More than HP Manager (c) by LostPersona",
        "app.header": "More than HP Manager",
        "app.subtitle": "Track HP, money, and spell slots, detach OBS windows, and sync values from a Google Doc.",
        "language.label": "Language",
        "language.en": "English",
        "language.ru": "Russian",
        "card.add_player": "Add Player",
        "card.players": "Players",
        "card.sync": "Document Sync Preview",
        "card.overlay_settings": "Fill Settings",
        "label.name": "Name",
        "label.current": "Current",
        "label.max": "Max",
        "label.temp": "Temp",
        "label.step": "Step",
        "label.source": "Google Doc link",
        "label.poll_seconds": "Poll seconds",
        "label.overlay_ratio": "Fill shape",
        "label.money_layout": "Money layout",
        "label.money_order": "Coin order",
        "label.spell_display_count": "Shown spell levels",
        "label.hp_font_size": "HP font size",
        "label.temp_hp_font_size": "Temp HP font size",
        "label.money_font_size": "Money font size",
        "label.spell_level_font_size": "Spell level font size",
        "label.spell_font_size": "Spell value font size",
        "label.spell_cell_scale": "Spell cell size",
        "label.window_behavior": "Window behavior",
        "action.add_to_dashboard": "Add To Dashboard",
        "action.player_window": "Player Window",
        "action.hide_window": "Hide Window",
        "action.overlay": "Fill",
        "action.hide_overlay": "Hide Fill",
        "action.money_window": "Money Window",
        "action.hide_money_window": "Hide Money Window",
        "action.edit_money": "Money",
        "action.spell_window": "Spell Window",
        "action.hide_spell_window": "Hide Spell Window",
        "action.edit_spell_slots": "Spell Slots",
        "action.apply": "Apply",
        "action.close": "Close",
        "action.remove": "Remove",
        "action.damage": "- HP",
        "action.heal": "+ HP",
        "action.fetch_doc": "Fetch Doc Now",
        "action.apply_parsed_lines": "Apply Parsed Lines",
        "action.load_example": "Load Example",
        "action.hide_sync": "Hide Sync",
        "action.show_sync": "Show Sync",
        "action.show_settings": "Show Settings",
        "action.hide_settings": "Hide Settings",
        "players.header": "Each player card keeps HP, fill, and spell slot controls together so OBS actions stay close to the character.",
        "sync.enable": "Enable automatic Google Doc sync",
        "sync.only_existing": "Only update existing players from sync data",
        "sync.help": "Only lines between `>>>` markers are parsed. Each character entry must start with `Name:` and can then include `Health:`, `Coins:`, and `Spell Slots:` in any order.\nMissing values default to zero, money supports `cc`, `sc`, `gc`, and spell slots use levels `1: current/max` through `9: current/max`.\nEnable \"Only update existing players\" to ignore unknown names instead of adding new dashboard entries from sync text.\nWhen sync mode is enabled, manual editing controls are hidden and the dashboard becomes display-focused.",
        "money.cc": "CC",
        "money.sc": "SC",
        "money.gc": "GC",
        "money.layout.stacked": "Separate lines",
        "money.layout.inline": "One line",
        "money.order.cc_sc_gc": "Copper, Silver, Gold",
        "money.order.gc_sc_cc": "Gold, Silver, Copper",
        "overlay.show_title": "Show character name above fill",
        "overlay.player_windows_topmost": "Keep player, money, and spell windows above other apps",
        "overlay.fill_windows_topmost": "Keep fill windows above other apps",
        "overlay.aspect.1:1": "Square (1:1)",
        "overlay.aspect.4:3": "Rectangle (4:3)",
        "overlay.aspect.3:4": "Portrait (3:4)",
        "overlay.window_title": "Fill: {name}",
        "player.window_title": "HP: {name}",
        "money.window_title": "Money: {name} ",
        "money.editor_title": "Money Editor: {name} ",
        "spell.window_title": "Spell Slots: {name}",
        "spell.editor_title": "Spell Slots Editor: {name}",
        "spell.level_label": "Level {level}",
        "player.temp_hp": "Temp HP: {temp_hp}",
        "player.summary": "Visible HP: {current_hp}/{max_hp}    Temp: {temp_hp}",
        "player.default_name": "Unnamed",
        "status.ready": "Ready",
        "status.added": "Added {name}.",
        "status.removed": "Removed {name}.",
        "status.money_saved": "Money updated for {name}.",
        "status.spell_slots_saved": "Spell slots updated for {name}.",
        "status.sync_applied": "Applied {applied} sync item(s) from the preview.",
        "status.sync_applied_skipped": "Applied {applied} sync item(s) from the preview and skipped {skipped} unknown name(s).",
        "status.sync_applied_with_issues": "Applied {applied} sync item(s), with {issues} parse issue(s).",
        "status.sync_applied_with_issues_skipped": "Applied {applied} sync item(s), skipped {skipped} unknown name(s), with {issues} parse issue(s).",
        "status.example_loaded": "Loaded example sync lines.",
        "status.language_changed": "Language switched to {language}.",
        "status.fetching_doc": "Fetching Google Doc...",
        "status.doc_fetched": "Fetched Google Doc and applied {applied} sync item(s).",
        "status.doc_fetched_skipped": "Fetched Google Doc, applied {applied} sync item(s), and skipped {skipped} unknown name(s).",
        "status.fetch_failed": "Google Doc fetch failed: {message}",
        "status.sync_source_missing": "Add a Google Doc link first.",
        "status.sync_hidden": "Document sync preview hidden.",
        "status.sync_shown": "Document sync preview shown.",
        "status.settings_hidden": "Fill settings hidden.",
        "status.settings_shown": "Fill settings shown.",
        "status.overlay_settings_saved": "Fill settings updated.",
        "dialog.parse_issues.title": "Parse issues",
        "dialog.parse_issues.message": "Line {line_number}: could not parse '{line}'",
        "dialog.fetch_failed.title": "Google Doc fetch failed",
        "error.sync.no_link": "No Google Doc link was provided.",
        "error.sync.bad_link": "Could not extract a Google Doc ID from the provided link.",
        "error.sync.access_denied": "Google denied access to the document export. Make sure the doc is shared so the app can read it.",
        "error.sync.not_found": "Google Doc not found. Check the link and document permissions.",
        "error.sync.http": "Google Doc export failed with HTTP {code}.",
        "error.sync.network": "Could not reach Google Docs: {reason}",
        "error.sync.html_response": "Received an HTML page instead of plain text. The document may require sign-in or block text export.",
        "error.sync.unknown": "Unexpected sync error: {message}",
    },
    "ru": {
        "app.title": "More than HP Manager (c) by LostPersona",
        "app.header": "More than HP Manager",
        "app.subtitle": "Отслеживайте HP, деньги и ячейки заклинаний, выносите окна для OBS и синхронизируйте значения из Google Doc.",
        "language.label": "Язык",
        "language.en": "Английский",
        "language.ru": "Русский",
        "card.add_player": "Добавить игрока",
        "card.players": "Игроки",
        "card.sync": "Предпросмотр синхронизации",
        "card.overlay_settings": "Настройки заливки",
        "label.name": "Имя",
        "label.current": "Текущее",
        "label.max": "Макс.",
        "label.temp": "Врем.",
        "label.step": "Шаг",
        "label.source": "Ссылка на Google Doc",
        "label.poll_seconds": "Интервал опроса",
        "label.overlay_ratio": "Форма заливки",
        "label.money_layout": "Расположение монет",
        "label.money_order": "Порядок монет",
        "label.spell_display_count": "Показывать уровни ячеек",
        "label.hp_font_size": "Размер шрифта HP",
        "label.temp_hp_font_size": "Размер шрифта врем. HP",
        "label.money_font_size": "Размер шрифта денег",
        "label.spell_level_font_size": "Размер шрифта уровней ячеек",
        "label.spell_font_size": "Размер шрифта значений ячеек",
        "label.spell_cell_scale": "Размер ячеек заклинаний",
        "label.window_behavior": "Поведение окон",
        "action.add_to_dashboard": "Добавить на панель",
        "action.player_window": "Окно HP",
        "action.hide_window": "Скрыть окно HP",
        "action.overlay": "Заливка",
        "action.hide_overlay": "Скрыть заливку",
        "action.money_window": "Окно денег",
        "action.hide_money_window": "Скрыть окно денег",
        "action.edit_money": "Деньги",
        "action.spell_window": "Окно ячеек",
        "action.hide_spell_window": "Скрыть окно ячеек",
        "action.edit_spell_slots": "Ячейки заклинаний",
        "action.apply": "Применить",
        "action.close": "Закрыть",
        "action.remove": "Удалить",
        "action.damage": "- HP",
        "action.heal": "+ HP",
        "action.fetch_doc": "Загрузить документ",
        "action.apply_parsed_lines": "Применить строки",
        "action.load_example": "Загрузить пример",
        "action.hide_sync": "Скрыть синхронизацию",
        "action.show_sync": "Показать синхронизацию",
        "action.show_settings": "Показать настройки",
        "action.hide_settings": "Скрыть настройки",
        "players.header": "В карточке игрока собраны HP, заливка и ячейки заклинаний, чтобы OBS-элементы были рядом с персонажем.",
        "sync.enable": "Включить автоматическую синхронизацию с Google Doc",
        "sync.only_existing": "Обновлять из синхронизации только существующих игроков",
        "sync.help": "Разбираются только строки между маркерами `>>>`. Каждая запись персонажа должна начинаться с `Имя:`, а дальше в любом порядке могут идти `Здоровье:`, `Монеты:` и `Ячейки заклинаний:`.\nОтсутствующие значения считаются нулевыми, для денег поддерживаются `cc`, `sc`, `gc` и русские `мм`, `см`, `зм`, а для ячеек уровни задаются как `1: текущее/макс` до `9: текущее/макс`.\nВключите \"Обновлять только существующих игроков\", чтобы неизвестные имена игнорировались и не создавали новых записей на панели.\nКогда режим синхронизации включен, ручные элементы редактирования скрываются, и панель работает как витрина значений.",
        "money.cc": "ММ",
        "money.sc": "СМ",
        "money.gc": "ЗМ",
        "money.layout.stacked": "Отдельные строки",
        "money.layout.inline": "Одна строка",
        "money.order.cc_sc_gc": "Медь, Серебро, Золото",
        "money.order.gc_sc_cc": "Золото, Серебро, Медь",
        "overlay.show_title": "Показывать имя персонажа над заливкой",
        "overlay.player_windows_topmost": "Держать окна игроков, денег и ячеек поверх других приложений",
        "overlay.fill_windows_topmost": "Держать окна заливки поверх других приложений",
        "overlay.aspect.1:1": "Квадрат (1:1)",
        "overlay.aspect.4:3": "Прямоугольник (4:3)",
        "overlay.aspect.3:4": "Портрет (3:4)",
        "overlay.window_title": "Заливка: {name}",
        "player.window_title": "HP: {name} ",
        "money.window_title": "Деньги: {name}",
        "money.editor_title": "Деньги Редактор: {name}",
        "spell.window_title": "Ячейки заклинаний: {name}",
        "spell.editor_title": "Ячейки заклинаний Редактор: {name}",
        "spell.level_label": "Уровень {level}",
        "player.temp_hp": "Временные HP: {temp_hp}",
        "player.summary": "Видимые HP: {current_hp}/{max_hp}    Врем.: {temp_hp}",
        "player.default_name": "Без имени",
        "status.ready": "Готово",
        "status.added": "Игрок {name} добавлен.",
        "status.removed": "Игрок {name} удален.",
        "status.money_saved": "Деньги обновлены для {name}.",
        "status.spell_slots_saved": "Ячейки заклинаний обновлены для {name}.",
        "status.sync_applied": "Применено объектов синхронизации из предпросмотра: {applied}.",
        "status.sync_applied_skipped": "Применено объектов синхронизации: {applied}, пропущено неизвестных имен: {skipped}.",
        "status.sync_applied_with_issues": "Применено объектов синхронизации: {applied}, проблем парсинга: {issues}.",
        "status.sync_applied_with_issues_skipped": "Применено объектов синхронизации: {applied}, пропущено неизвестных имен: {skipped}, проблем парсинга: {issues}.",
        "status.example_loaded": "Пример строк синхронизации загружен.",
        "status.language_changed": "Язык переключен: {language}.",
        "status.fetching_doc": "Загрузка Google Doc...",
        "status.doc_fetched": "Google Doc загружен, применено объектов синхронизации: {applied}.",
        "status.doc_fetched_skipped": "Google Doc загружен, применено объектов синхронизации: {applied}, пропущено неизвестных имен: {skipped}.",
        "status.fetch_failed": "Не удалось загрузить Google Doc: {message}",
        "status.sync_source_missing": "Сначала добавьте ссылку на Google Doc.",
        "status.sync_hidden": "Предпросмотр синхронизации скрыт.",
        "status.sync_shown": "Предпросмотр синхронизации показан.",
        "status.settings_hidden": "Настройки заливки скрыты.",
        "status.settings_shown": "Настройки заливки показаны.",
        "status.overlay_settings_saved": "Настройки заливки обновлены.",
        "dialog.parse_issues.title": "Проблемы парсинга",
        "dialog.parse_issues.message": "Строка {line_number}: не удалось разобрать '{line}'",
        "dialog.fetch_failed.title": "Не удалось загрузить Google Doc",
        "error.sync.no_link": "Ссылка на Google Doc не указана.",
        "error.sync.bad_link": "Не удалось извлечь идентификатор Google Doc из указанной ссылки.",
        "error.sync.access_denied": "Google не дал доступ к экспорту документа. Убедитесь, что документ открыт для чтения приложением.",
        "error.sync.not_found": "Google Doc не найден. Проверьте ссылку и права доступа к документу.",
        "error.sync.http": "Экспорт Google Doc завершился ошибкой HTTP {code}.",
        "error.sync.network": "Не удалось связаться с Google Docs: {reason}",
        "error.sync.html_response": "Вместо текста пришла HTML-страница. Возможно, документ требует входа или блокирует текстовый экспорт.",
        "error.sync.unknown": "Непредвиденная ошибка синхронизации: {message}",
    },
}


def normalize_locale(locale: str | None) -> str:
    if locale in SUPPORTED_LOCALES:
        return locale
    return DEFAULT_LOCALE


class Localizer:
    def __init__(self, locale: str | None = None) -> None:
        self.locale = normalize_locale(locale)

    def set_locale(self, locale: str) -> None:
        self.locale = normalize_locale(locale)

    def text(self, key: str, **kwargs: object) -> str:
        value = TRANSLATIONS.get(self.locale, {}).get(key)
        if value is None:
            value = TRANSLATIONS[DEFAULT_LOCALE].get(key, key)
        return value.format(**kwargs)

    def locale_name(self, locale: str) -> str:
        code = normalize_locale(locale)
        return self.text(f"language.{code}")
